allowBuilds:
  '@clerk/shared': true
  '@google/genai': true
  '@mongodb-js/zstd': true
  core-js-pure: true
  esbuild: true
  node-liblzma: true
  protobufjs: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - '@flue/cli@1.0.0-beta.8'
  - '@flue/react@1.0.0-beta.8'
  - '@flue/runtime@1.0.0-beta.8'
  - '@flue/sdk@1.0.0-beta.8'
